language: python
python:
  - '3.7'
cache:
  - pip
install:
  - pip install -r requirements.txt
script:
  - mypy . --disallow-untyped-defs
before_deploy:
  - openssl aes-256-cbc -K $encrypted_db2095f63ba3_key -iv $encrypted_db2095f63ba3_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  - provider: script
    skip_cleanup: true
    script: deploy_local.sh
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: ssh ubuntu@ec2-18-135-101-136.eu-west-2.compute.amazonaws.com 'bash ./deploy.sh'
    on:
      branch: master
