version: 1

formatters:
    standard:
        format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'

handlers:
    file_handler_main:
        class: logging.FileHandler
        level: INFO
        formatter: standard
        filename: logs/main.log
        mode: w+

root:
    level: INFO
    handlers: [file_handler_main]
